services:

  postgres:

    image: pgvector/pgvector:pg16

    container_name: docmind-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: docmind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4142

    ports:
      - "5433:5432"

    volumes:
      - docmind-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

volumes:
  docmind-data:
