spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/docmind
    username: postgres
    password: 4142

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:

  storage:
    root: storage

  ai:
    top-k: 10
    chunk-size: 800
    chunk-overlap: 150

logging:
  level:
    org.springframework.ai: INFO
    org.flywaydb: DEBUG