spring.application.name=docmind
# ===========================
# Database
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5433/docmind
spring.datasource.username=postgres
spring.datasource.password=4142
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# ===========================
# Multipart
# ===========================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# ===========================
# Ollama
# ===========================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:1.7b
spring.ai.ollama.embedding.options.model=nomic-embed-text
# ===========================
# Application
# ===========================
app.upload.directory=uploads
app.chunk.size=800
app.chunk.overlap=150
app.rag.top-k=5