spring.application.name=docmind

# ===========================
# Database
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5433/docmind
spring.datasource.username=postgres
spring.datasource.password=4142

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===========================
# Multipart
# ===========================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===========================
# Ollama
# ===========================
app.ollama.base-url=http://localhost:11434
app.ollama.chat-model=qwen3:1.7b
app.ollama.embedding-model=nomic-embed-text

spring.ai.ollama.base-url=${app.ollama.base-url}
spring.ai.ollama.chat.options.model=${app.ollama.chat-model}
spring.ai.ollama.embedding.options.model=${app.ollama.embedding-model}

# ===========================
# RAG
# ===========================
app.chunk.size=800
app.chunk.overlap-sentences=2

app.rag.top-k=8
app.rag.similarity-threshold=0.85

# ===========================
# Storage
# ===========================
app.storage.directory=uploads
app.storage.persist-files=false

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

springdoc.default-produces-media-type=application/json
